### ISSUE TITLE
Mistake

### ISSUE THREAD

**Issue by Rosu-Catalin** [PlaceholderAPI-Expansions/ASkyblock-Expansion#6]
%askyblock_members_online% 
%askyblock_members_max% 
%askyblock_team_leader% 
%askyblock_has_team%

don't work in the latest version.

**Comment by PrayaAmadigaPitasa** [comment]
I'll check it

**Comment by PrayaAmadigaPitasa** [comment]
are you sure it's on latest version? I have tried it and works

**Comment by aBooDyy** [comment]
Hey there,
the expansion isnt updated in the cloud (hope someone does soon) but if u want it, i have compiled it and u can download it from here http://aboodyy.net/PAPI-Expansion-ASkyblock.jar

**Comment by Andre601** [comment]
Since the expansion is updated and no answers where given, will we now assume that the issue is resolved.
If it isn't please respond here so that we can reopen it.
